// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}
